spring:
  main:
    banner-mode: "OFF"
  output:
    ansi:
      enabled: DETECT

logging:
  level:
    root: INFO
    inditex.infrastructure.configuration: DEBUG
  file:
    name: "log/inditex-test.log"
  logback:
    rollingpolicy:
      total-size-cap: 4 GB
      max-file-size: 100 MB
      max-history: 7

application:
  date-time:
    zoneId: "CET"

server:
  port: 8081

endpoint:
  status:
    path: "/status"

  public:
    v1:
      path: "/public/v1"
      price:
        path:
          base: "${endpoint.public.v1.path}/price"